name: Terraform CI with Terragrunt

on:
  workflow_dispatch: # Manual trigger only

jobs:
  terraform:
    name: Terragrunt Deploy
    runs-on: ubuntu-latest
    env:
      GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_REGION: ${{ secrets.GCP_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set gcloud project and region
        run: |
          gcloud config set project $GOOGLE_PROJECT
          gcloud config set compute/region $GOOGLE_REGION

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Install Terragrunt
        run: |
          TG_VERSION="0.84.1"
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt

      - name: Terragrunt Init network
        run: terragrunt init --non-interactive --working-dir=live/dev/network

      - name: Terragrunt Apply network
        run: terragrunt apply --auto-approve --non-interactive --working-dir=live/dev/network

      - name: Terragrunt Init firewall
        run: terragrunt init --non-interactive --working-dir=live/dev/firewall

      - name: Terragrunt Apply firewall
        run: terragrunt apply --auto-approve --non-interactive --working-dir=live/dev/firewall

      - name: Terragrunt Init gke-cluster
        run: terragrunt init --non-interactive --working-dir=live/dev/gke-cluster

      - name: Terragrunt Apply gke-cluster
        run: terragrunt apply --auto-approve --non-interactive --working-dir=live/dev/gke-cluster
