name: Terragrunt Destroy (Exclude GKE Cluster)

on:
  workflow_dispatch:

jobs:
  terragrunt-destroy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_REGION: ${{ secrets.GCP_REGION }}
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      BUCKET_NAME: samurai-og1-bucket

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set gcloud project & region
        run: |
          gcloud config set project $GOOGLE_PROJECT
          gcloud config set compute/region $GOOGLE_REGION

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Install Terragrunt
        run: |
          TG_VERSION="0.84.1"
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt

      - name: Check if state files exist
        id: check_state
        run: |
          modules=("firewall" "network")
          missing=0
          for module in "${modules[@]}"; do
            echo "Checking $module state..."
            if ! gsutil ls gs://$BUCKET_NAME/$module/terraform.tfstate >/dev/null 2>&1; then
              echo "❌ No state found for $module"
              missing=1
            else
              echo "✅ State found for $module"
            fi
          done
          if [ "$missing" -eq 1 ]; then
            echo "Some state files missing. Skipping destroy."
            exit 0
          fi

      - name: Destroy firewall rules only
        run: |
          cd live/dev/firewall
          terragrunt destroy --auto-approve --non-interactive

      - name: Destroy network only
        run: |
          cd live/dev/network
          terragrunt destroy --auto-approve --non-interactive
